#' Write Transition Probability Estimates to Excel
#' 
#' @description Generates a multi-sheet Excel workbook with a professional cover sheet 
#' including detailed methodological metadata for reproducibility.
#'
#' In addition to the curated parameter table on the cover sheet, a 'Run
#' Configuration' sheet is auto-generated by iterating over every element of
#' `config`, together with the package version, the resolved initiation trend
#' model, the bootstrap seed and the run time. Because it is generated rather
#' than curated, a parameter added to the config in future cannot silently
#' fall out of the report; diffing this sheet between two workbooks is the
#' definitive check of whether two deliveries used the same settings. All
#' config access uses `[[` because `$` partial-matches list names (the old
#' table reported `kn_samp` as `kn` for exactly this reason).
#' @param config Configuration list containing metadata and model parameters.
#' @param init_res Initiation results list/dataframe.
#' @param quit_res Quitting results list/dataframe.
#' @param relapse_res Relapse results list/dataframe.
#' @param net_init_dt Optional net initiation table (can be NULL).
#' @param quit_no_init Optional quitting without initiation table (can be NULL).
#' 
#' @import openxlsx
#' @importFrom utils packageVersion
#' @export
write_excel_report <- function(config, init_res, quit_res, relapse_res, 
                               net_init_dt = NULL, quit_no_init = NULL) {
  
  # 1. Initialize Workbook
  wb <- createWorkbook()
  
  # =========================================================================
  # STYLES DEFINITION (University of Sheffield Brand Toolkit)
  # =========================================================================
  # Core Brand Colours (Approximated to UoS brand guidelines)
  brand_violet    <- "#440099" # Primary prestige brand colour
  dark_violet     <- "#22004C" # Deep contrast for text
  electric_violet <- "#6B00F2" # Vibrant accent colour
  powder_violet   <- "#E6D9F2" # Soft background for tables
  gallery_white   <- "#FFFFFF" # Clean background
  misty_grey      <- "#F2F2F2" # Soft neutral for citation boxes
  
  # Toolkit specifies 'Source Sans' / 'Source Serif'. 
  # Arial is used here as a bulletproof web-safe fallback for Excel.
  brand_font <- "Arial" 
  
  style_title <- createStyle(fontName = brand_font, fontSize = 16, textDecoration = "bold", 
                             fontColour = brand_violet)
  
  style_affil <- createStyle(fontName = brand_font, fontSize = 10, fontColour = dark_violet, 
                             wrapText = TRUE)
  
  style_contact <- createStyle(fontName = brand_font, fontSize = 10, fontColour = electric_violet, 
                               textDecoration = "bold", wrapText = TRUE)
  
  # Professional citation box style
  style_cite_box <- createStyle(fontName = brand_font, fontSize = 10, fontColour = "#000000",
                                fgFill = misty_grey, border = "LeftRightTopBottom", 
                                borderColour = "#CCCCCC", wrapText = TRUE, valign = "top")
  
  style_cite_header <- createStyle(fontName = brand_font, fontSize = 10, fontColour = dark_violet,
                                   textDecoration = "bold", fgFill = misty_grey, wrapText = TRUE)
  
  # Heavy bold headers with the primary Brand Violet
  style_header <- createStyle(fontName = brand_font, textDecoration = "bold", fontColour = gallery_white, 
                              fgFill = brand_violet, halign = "left", valign = "center",
                              border = "TopBottom", borderColour = brand_violet)
  
  # Softer Powder Violet for data table column headers
  style_col_header <- createStyle(fontName = brand_font, textDecoration = "bold", fontColour = dark_violet, 
                                  fgFill = powder_violet, halign = "center", border = "Bottom", borderColour = brand_violet)
  
  style_text <- createStyle(fontName = brand_font, fontSize = 10, wrapText = TRUE, valign = "top")
  
  style_num <- createStyle(numFmt = "0.0000")
  
  # =========================================================================
  # 2. COVER SHEET CONSTRUCTION
  # =========================================================================
  sheet_name <- "Cover Sheet"
  addWorksheet(wb, sheet_name)
  showGridLines(wb, sheet_name, showGridLines = FALSE)
  
  # --- A. Title, Date & Package Version ---
  # No hard-coded fallback: a wrong version number on a delivery is worse than
  # an honest "unknown".
  pkg_ver <- tryCatch(as.character(utils::packageVersion("smktrans")),
                      error = function(e) "unknown (smktrans not installed)")
  run_date <- format(Sys.Date(), "%d %B %Y")
  current_year <- format(Sys.Date(), "%Y")
  
  title_text <- paste0("Smoking Transition Probability Estimates (v", pkg_ver, ")")
  writeData(wb, sheet_name, title_text, startRow = 1, startCol = 1)
  addStyle(wb, sheet_name, style_title, rows = 1, cols = 1)
  
  date_text <- paste0("Report Generated: ", run_date)
  writeData(wb, sheet_name, date_text, startRow = 2, startCol = 1)
  addStyle(wb, sheet_name, style_affil, rows = 2, cols = 1)
  
  # --- B. Affiliation & Contact ---
  affiliation_text <- paste(
    "Sheffield Addictions Research Group (SARG)",
    "Sheffield Centre for Health and Related Research (SCHARR)",
    "School of Medicine and Population Health, The University of Sheffield",
    "Western Bank, Sheffield, S10 2TN, United Kingdom",
    sep = "\n"
  )
  writeData(wb, sheet_name, affiliation_text, startRow = 4, startCol = 1)
  addStyle(wb, sheet_name, style_affil, rows = 4, cols = 1)
  setRowHeights(wb, sheet_name, rows = 4, heights = 60)
  
  contact_text <- "Contact: Dr Duncan Gillespie (duncan.gillespie@sheffield.ac.uk)"
  writeData(wb, sheet_name, contact_text, startRow = 5, startCol = 1)
  addStyle(wb, sheet_name, style_contact, rows = 5, cols = 1)
  
  # --- C. HOW TO CITE ---
  row_idx <- 7
  writeData(wb, sheet_name, "1. How to Cite", startRow = row_idx, startCol = 1)
  addStyle(wb, sheet_name, style_header, rows = row_idx, cols = 1:4)
  
  row_idx <- row_idx + 1
  
  write_cite_row <- function(wb, sheet, row, text, height = 30, style = style_cite_box) {
    writeData(wb, sheet, text, startRow = row, startCol = 1)
    mergeCells(wb, sheet, cols = 1:4, rows = row)
    addStyle(wb, sheet, style, rows = row, cols = 1)
    setRowHeights(wb, sheet, rows = row, heights = height)
  }
  
  intro_text <- "If you use the smktrans estimates in your research, please cite our peer-reviewed modelling papers. These publications validate the use of these estimates in policy appraisal contexts:"
  write_cite_row(wb, sheet_name, row_idx, intro_text, height = 30, style = style_cite_header)
  
  row_idx <- row_idx + 1
  paper1 <- "Chen RKL, Morris D, Angus C, Gilmore A, Hiscock R, Holmes J, Langley TE, Pryce R, Wilson LB, Brennan A, Gillespie D (2026). Reducing the exceptional affordability of hand-rolling tobacco using tax escalators: a health and economic impact modelling study for England. Tobacco Control. DOI: 10.1136/tc-2025-059670"
  write_cite_row(wb, sheet_name, row_idx, paper1, height = 45)
  
  row_idx <- row_idx + 1
  paper2 <- "Gillespie D, Morris D, Angus C, Wilson L, Chen RKL, Leeming G, Holmes J, Brennan A (2025). Model-based appraisal of the potential effects of minimum pricing for tobacco in Scotland. Tobacco Control. DOI: 10.1136/tc-2024-059252"
  write_cite_row(wb, sheet_name, row_idx, paper2, height = 30)
  
  row_idx <- row_idx + 1
  soft_intro <- "To cite the smktrans software package specifically:"
  write_cite_row(wb, sheet_name, row_idx, soft_intro, height = 15, style = style_cite_header)
  
  row_idx <- row_idx + 1
  soft_cite <- paste0("Gillespie, D., and Brennan, A. (", current_year, "). smktrans: An R Package for estimating smoking state transition probabilities (v", pkg_ver, "). University of Sheffield. https://doi.org/10.17605/OSF.IO/YGXQ9")
  write_cite_row(wb, sheet_name, row_idx, soft_cite, height = 30)
  
  row_idx <- row_idx + 1
  tech_intro <- "To cite the full technical documentation for the underlying model:"
  write_cite_row(wb, sheet_name, row_idx, tech_intro, height = 15, style = style_cite_header)
  
  row_idx <- row_idx + 1
  tech_cite <- "Gillespie, D. & Brennan, A. (Year). The Sheffield Tobacco Policy Model (STPM): full technical documentation. Documentation version number [x.x.x]. University of Sheffield. DOI: 10.17605/OSF.IO/FR7WN"
  write_cite_row(wb, sheet_name, row_idx, tech_cite, height = 30)
  
  row_idx <- row_idx + 1
  note_cite <- "(Note: The technical documentation is a living document. Please cite the year and version of the report you used.)"
  write_cite_row(wb, sheet_name, row_idx, note_cite, height = 15)
  
  # --- D. About This Dataset ---
  row_idx <- row_idx + 2
  writeData(wb, sheet_name, "2. About this Dataset", startRow = row_idx, startCol = 1)
  addStyle(wb, sheet_name, style_header, rows = row_idx, cols = 1:4)
  
  desc_text <- paste(
    "This workbook contains estimated annual probabilities for smoking state transitions used in the STAPM microsimulation model.",
    "Estimates are derived using methods in the R package 'smktrans' fitted to repeat annual cross-sectional survey data.",
    "These probabilities represent the likelihood of an individual changing their smoking status within a one-year period.",
    sep = " "
  )
  row_idx <- row_idx + 1
  writeData(wb, sheet_name, desc_text, startRow = row_idx, startCol = 1)
  mergeCells(wb, sheet_name, cols = 1:4, rows = row_idx) 
  addStyle(wb, sheet_name, style_text, rows = row_idx, cols = 1)
  setRowHeights(wb, sheet_name, rows = row_idx, heights = 60)
  
  # --- E. Sheet Guide ---
  row_idx <- row_idx + 2
  writeData(wb, sheet_name, "3. Worksheet Guide", startRow = row_idx, startCol = 1)
  addStyle(wb, sheet_name, style_header, rows = row_idx, cols = 1:4)
  
  guide_df <- data.frame(
    Worksheet = c("Run Configuration", "Initiation", "Quitting", "Relapse"),
    Description = c(
      "Auto-generated verbatim record of every configuration parameter used for this run. Diff this sheet between workbooks to compare deliveries.",
      "Probability of a 'Never Smoker' becoming a 'Current Smoker' (Start).",
      "Probability of a 'Current Smoker' becoming a 'Former Smoker' (Quit).",
      "Probability of a 'Former Smoker' becoming a 'Current Smoker' (Relapse), dependent on time since quitting."
    )
  )
  
  if (!is.null(net_init_dt)) {
    guide_df <- rbind(guide_df, data.frame(Worksheet = "Net Initiation", Description = "Net initiation probabilities (Initiation - Quitting)."))
  }
  if (!is.null(quit_no_init)) {
    guide_df <- rbind(guide_df, data.frame(Worksheet = "Quit (No Init)", Description = "Quitting probabilities calculated without initiation adjustment."))
  }
  
  row_idx <- row_idx + 1
  writeData(wb, sheet_name, guide_df, startRow = row_idx, startCol = 1, headerStyle = style_col_header)
  addStyle(wb, sheet_name, style_text, rows = (row_idx+1):(row_idx+nrow(guide_df)), cols = 2)
  
  # --- F. Variable Definitions ---
  row_idx <- row_idx + nrow(guide_df) + 2
  writeData(wb, sheet_name, "4. Variable Definitions", startRow = row_idx, startCol = 1)
  addStyle(wb, sheet_name, style_header, rows = row_idx, cols = 1:4)
  
  var_df <- data.frame(
    Variable = c(
      "age", 
      "sex", 
      "imd_quintile", 
      "time_since_quit", 
      "p_[metric]", 
      "p_[metric]_lower / _upper", 
      "p_[metric]_se"
    ),
    Definition = c(
      "Age of the individual in years (single year of age).",
      "Biological sex (Men / Women).",
      "Index of Multiple Deprivation Quintile. 1 = Least Deprived, 5 = Most Deprived.",
      "Number of years since the individual last quit smoking (Relapse only). 0 = quit for <1 year.",
      "The estimated baseline annual probability (0.0 to 1.0).",
      "The 95% empirical confidence intervals, derived from bootstrapping.",
      "The standard error of the estimate, designed for use in Probabilistic Sensitivity Analysis (PSA)."
    )
  )
  row_idx <- row_idx + 1
  writeData(wb, sheet_name, var_df, startRow = row_idx, startCol = 1, headerStyle = style_col_header)
  
  # =========================================================================
  # 2B. METHODOLOGICAL PARAMETERS
  # =========================================================================
  # Values are read with config[[...]] throughout, never config$... . The $
  # operator partial-matches list names, and that is not hypothetical: the old
  # table asked for config$kn, which matched kn_samp and reported a bootstrap
  # sample count of 1000 as an "effective sample size" parameter that was not
  # set at all.
  
  fmt <- function(x) {
    if (is.null(x)) return("not set")
    if (is.list(x)) return(paste0("<list of ", length(x), ">"))
    if (length(x) == 0) return("empty")
    if (is.numeric(x) && length(x) > 3) {
      xs <- sort(x)
      # A contiguous integer sequence reads better as a range than as 79
      # comma-separated numbers (trend_grid_ages, trend_keep_years, ...).
      if (all(abs(diff(xs) - 1) < 1e-9)) {
        return(paste0(min(xs), "-", max(xs), " (", length(xs), " values)"))
      }
    }
    if (length(x) > 12) {
      return(paste0(paste(utils::head(x, 12), collapse = ", "),
                    ", ... (", length(x), " values)"))
    }
    paste(as.character(x), collapse = ", ")
  }
  
  # Resolve the initiation model actually used. Under "auto" the base run
  # writes its choice to disk for the bootstrap (see init_resolve_model), so
  # the report can and should say which model the data selected, not just that
  # selection was automatic.
  resolved_model <- NA_character_
  if (identical(config[["init_model_choice"]], "auto")) {
    choice_file <- file.path(config[["path"]], "outputs",
                             paste0("init_model_choice_", config[["country"]], ".rds"))
    if (file.exists(choice_file)) {
      resolved_model <- tryCatch(as.character(readRDS(choice_file)),
                                 error = function(e) NA_character_)
    }
  }
  model_choice_txt <- if (identical(config[["init_model_choice"]], "auto")) {
    if (!is.na(resolved_model)) {
      paste0("auto (resolved: ", resolved_model, ")")
    } else {
      "auto (resolved choice file not found)"
    }
  } else {
    fmt(config[["init_model_choice"]])
  }
  
  # The age trend limit means different things depending on where it sits, so
  # say which situation this run is in rather than leaving the reader to work
  # it out from the numbers.
  atl_init <- config[["age_trend_limit_init"]]
  ref_age  <- config[["ref_age"]]
  desc_atl_init <- if (!is.null(atl_init) && !is.null(ref_age) && atl_init >= ref_age) {
    "Upper age of the fitted initiation trend. Set equal to the maximum initiation age (ref_age), so no carry-forward is applied: all ages are estimated."
  } else {
    "Upper age of the fitted initiation trend. Ages above this carry the value at the limit forward unchanged (LOCF)."
  }
  
  atl_quit <- config[["age_trend_limit_quit"]]
  max_age  <- config[["max_age"]]
  desc_atl_quit <- if (!is.null(atl_quit) && !is.null(max_age) && atl_quit >= max_age - 1) {
    "Upper age of the fitted quitting trend. Set to the oldest modelled age, so no carry-forward is applied: all ages are estimated."
  } else {
    "Upper age of the fitted quitting trend. Ages above this carry the value at the limit forward unchanged (LOCF)."
  }
  
  # The relapse forecast is stationary (see estimate_relapse for why), which
  # makes the trend scaler identically 1 and this parameter inert. Recorded
  # for completeness, flagged so nobody reads it as shaping the outputs.
  desc_atl_relapse <- paste(
    "Recorded for completeness but INACTIVE: the relapse forecast is",
    "stationary (the jump-off surface is held flat), so the trend scaler",
    "equals 1 and this parameter does not affect the published relapse",
    "probabilities, which retain age variation to the oldest modelled age."
  )
  
  meta_df <- data.frame(
    Category = c(
      "Software",
      "Data Source", "Data Source", "Data Source", "Data Source",
      "Projection", "Projection", "Projection", "Projection",
      "Initiation Model", "Initiation Model", "Initiation Model", "Initiation Model", "Initiation Model", "Initiation Model",
      "Quitting Model", "Quitting Model", "Quitting Model", "Quitting Model",
      "Relapse Model", "Relapse Model", "Relapse Model", "Relapse Model",
      "Uncertainty", "Uncertainty", "Uncertainty"
    ),
    Parameter = c(
      "Package Version",
      "Region", "Survey Source", "Survey Years", "Modelled Age Range",
      "Time Horizon", "Trend Continuity Limit", "Prevalence Trend Last Year", "Prevalence Trend Extrapolation",
      "Trend Model Choice", "Forecast Type", "Smooth Dims (Age, Year)", "Age Smoothing (k)", "Max Initiation Age (ref_age)", "Age Trend Limit",
      "Forecast Type", "Smooth Dims (Age, Year)", "Age Smoothing (k)", "Age Trend Limit",
      "Forecast Type", "Smooth Dims (Age, Year)", "Age Smoothing (k)", "Age Trend Limit",
      "Bootstrap Iterations (kn_samp)", "Master Seed", "Interval Type"
    ),
    Value = c(
      fmt(pkg_ver),
      fmt(config[["country"]]), fmt(config[["survey_name"]]),
      paste(config[["first_year"]], "-", config[["last_year"]]),
      paste(config[["min_age"]], "-", config[["max_age"]]),
      fmt(config[["time_horizon"]]), fmt(config[["cont_limit"]]),
      fmt(if (is.null(config[["trend_last_year"]])) config[["last_year"]] else config[["trend_last_year"]]),
      fmt(isTRUE(config[["trend_allow_extrapolation"]])),
      model_choice_txt, "continuing", fmt(config[["smooth_rate_dim_init"]]),
      fmt(config[["k_smooth_age_init"]]), fmt(config[["ref_age"]]), fmt(atl_init),
      "continuing", fmt(config[["smooth_rate_dim_quit"]]),
      fmt(config[["k_smooth_age_quit"]]), fmt(atl_quit),
      "stationary", fmt(config[["smooth_rate_dim_relapse"]]),
      fmt(config[["k_smooth_age_relapse"]]), fmt(config[["age_trend_limit_relapse"]]),
      fmt(config[["kn_samp"]]), fmt(config[["seed"]]),
      "95% empirical bootstrap percentile"
    ),
    Description = c(
      "smktrans version.",
      "Target population.", "Primary dataset.", "Range of survey data used.",
      "Youngest and oldest modelled ages.",
      "Final projected year.",
      "Projected year after which the fitted time trend is held constant.",
      "Last year of the fitted smoking prevalence surface (beyond the survey data if extrapolation is on).",
      "Whether the prevalence trend model predicts beyond the observed age/year range.",
      "Ever-smoking trend model: the setting and, under auto, the model the selection procedure chose.",
      "Initiation time trend continues to the continuity limit, then holds.",
      "Smoothing window dimensions.", "Degree of age smoothing (rotation). 0 = none.",
      "Initiation is assumed to cease at this age; probabilities above it are zero.",
      desc_atl_init,
      "Quitting time trend continues to the continuity limit, then holds.",
      "Smoothing window dimensions.", "Degree of age smoothing.",
      desc_atl_quit,
      "The jump-off relapse surface is held flat over the projection (single-study input has no time dimension).",
      "Smoothing window dimensions.", "Degree of age smoothing.",
      desc_atl_relapse,
      "Number of bootstrap resamples. Central estimates are bootstrap medians.",
      "Master random seed. The exported estimates are bootstrap medians, so the seed is part of their identity: same seed + same config + same version = same numbers.",
      "Lower/upper bounds are the 2.5th and 97.5th percentiles of the bootstrap draws; _se is their standard deviation."
    )
  )
  
  # The old code wrote this table one row below the START of the variable
  # definitions table, overwriting its seven data rows - the July 2026
  # workbooks are missing the variable definitions for exactly this reason.
  # Advance past var_df (header + rows) before writing anything else.
  row_idx <- row_idx + nrow(var_df) + 2
  writeData(wb, sheet_name, "5. Methodological Parameters", startRow = row_idx, startCol = 1)
  addStyle(wb, sheet_name, style_header, rows = row_idx, cols = 1:4)
  
  row_idx <- row_idx + 1
  writeData(wb, sheet_name, meta_df, startRow = row_idx, startCol = 1, headerStyle = style_col_header)
  addStyle(wb, sheet_name, style_text, rows = (row_idx + 1):(row_idx + nrow(meta_df)), cols = 4)
  
  row_idx <- row_idx + nrow(meta_df) + 2
  note_cfg <- "A complete, auto-generated dump of every run configuration parameter is on the 'Run Configuration' sheet. That sheet is the authoritative record for comparing deliveries; this table is a curated summary."
  writeData(wb, sheet_name, note_cfg, startRow = row_idx, startCol = 1)
  mergeCells(wb, sheet_name, cols = 1:4, rows = row_idx)
  addStyle(wb, sheet_name, style_cite_header, rows = row_idx, cols = 1)
  setRowHeights(wb, sheet_name, rows = row_idx, heights = 30)
  
  # --- H. Column Width Adjustment ---
  setColWidths(wb, sheet_name, cols = 1, widths = 85) 
  setColWidths(wb, sheet_name, cols = 2, widths = 50)
  setColWidths(wb, sheet_name, cols = 3, widths = 35)
  setColWidths(wb, sheet_name, cols = 4, widths = 100)
  
  # =========================================================================
  # 2C. RUN CONFIGURATION SHEET (verbatim dump)
  # =========================================================================
  # Every element of config, written out by iterating names(config). The point
  # of generating it rather than curating it is that a parameter added to the
  # config in future CANNOT silently fall out of the report - which is exactly
  # what happened to age_trend_limit_init in the curated table. Two deliveries
  # differ visibly and completely in this sheet.
  
  sheet_cfg <- "Run Configuration"
  addWorksheet(wb, sheet_cfg)
  showGridLines(wb, sheet_cfg, showGridLines = FALSE)
  
  run_rows <- data.frame(
    Parameter = c("package_version", "resolved_init_model", "report_generated", "r_version"),
    Value = c(
      pkg_ver,
      if (identical(config[["init_model_choice"]], "auto") && !is.na(resolved_model)) resolved_model else fmt(config[["init_model_choice"]]),
      format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
      paste0(R.version$major, ".", R.version$minor)
    ),
    Source = c("environment", "selected by base run", "environment", "environment"),
    stringsAsFactors = FALSE
  )
  
  cfg_names <- names(config)
  cfg_rows <- data.frame(
    Parameter = cfg_names,
    Value = vapply(cfg_names, function(nm) fmt(config[[nm]]), character(1)),
    Source = "config",
    stringsAsFactors = FALSE
  )
  
  cfg_df <- rbind(run_rows, cfg_rows)
  
  writeData(wb, sheet_cfg, paste0("Run configuration: ", config[["country"]]),
            startRow = 1, startCol = 1)
  addStyle(wb, sheet_cfg, style_title, rows = 1, cols = 1)
  
  cfg_note <- paste(
    "Auto-generated verbatim record of the configuration this workbook was built from,",
    "plus the software version, the resolved initiation trend model, and the run time.",
    "To establish whether two deliveries used the same settings, diff this sheet.",
    "Long integer sequences are summarised as ranges."
  )
  writeData(wb, sheet_cfg, cfg_note, startRow = 2, startCol = 1)
  mergeCells(wb, sheet_cfg, cols = 1:3, rows = 2)
  addStyle(wb, sheet_cfg, style_affil, rows = 2, cols = 1)
  setRowHeights(wb, sheet_cfg, rows = 2, heights = 45)
  
  writeData(wb, sheet_cfg, cfg_df, startRow = 4, startCol = 1, headerStyle = style_col_header)
  addStyle(wb, sheet_cfg, style_text, rows = 5:(4 + nrow(cfg_df)), cols = 1:3, gridExpand = TRUE)
  freezePane(wb, sheet_cfg, firstActiveRow = 5)
  setColWidths(wb, sheet_cfg, cols = 1, widths = 35)
  setColWidths(wb, sheet_cfg, cols = 2, widths = 55)
  setColWidths(wb, sheet_cfg, cols = 3, widths = 22)
  
  # =========================================================================
  # 3. DATA SHEETS
  # =========================================================================
  add_data_sheet <- function(wb, s_name, res_obj) {
    addWorksheet(wb, s_name)
    df <- if (inherits(res_obj, "data.frame")) res_obj else if ("data" %in% names(res_obj)) res_obj$data else data.frame(Warning = "Data not found")
    
    writeData(wb, s_name, df, headerStyle = style_col_header)
    freezePane(wb, s_name, firstRow = TRUE)
    
    p_cols <- grep("^p_", names(df))
    if (length(p_cols) > 0) addStyle(wb, s_name, style_num, rows = 2:(nrow(df) + 1), cols = p_cols, gridExpand = TRUE)
    
    setColWidths(wb, s_name, cols = 1:ncol(df), widths = 25)
  }
  
  add_data_sheet(wb, "Initiation", init_res)
  add_data_sheet(wb, "Quitting", quit_res)
  add_data_sheet(wb, "Relapse", relapse_res)
  
  if (!is.null(net_init_dt)) add_data_sheet(wb, "Net Initiation", net_init_dt)
  if (!is.null(quit_no_init)) add_data_sheet(wb, "Quit (No Init)", quit_no_init)
  
  # =========================================================================
  # 4. SAVE
  # =========================================================================
  out_dir <- file.path("transition_probability_estimates", "outputs")
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  out_file <- file.path(out_dir, paste0("SmokeStateTransProbs_", config[["country"]], "_", Sys.Date(), ".xlsx"))
  saveWorkbook(wb, out_file, overwrite = TRUE)
}